# -*- coding: utf-8 -*-
"""backtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GM-ctNMohsRfTY5xOpfBttfLup-SIuW
"""

# Importing libraries
import pandas as pd
import numpy as np
import itertools
import json
import matplotlib.pyplot as plt

# Loading and preprocessing market data from CSV
df = pd.read_csv("l1_day.csv")

# Sorting by timestamp and venue ID, and keeping only the first quote per venue per timestamp
df = df.sort_values(by=['ts_event', 'publisher_id'])
df = df.drop_duplicates(subset=['ts_event', 'publisher_id'], keep='first')

# Groupping data into snapshots by timestamp
snapshots = list(df.groupby('ts_event'))

# Defining constants
ORDER_SIZE = 5000       # Number of shares to buy
STEP = 100              # Granularity of allocation (step size)
FEE = 0.003             # Fee per share traded
REBATE = 0.002          # Rebate for unexecuted shares

# Defining Venue class to represent order book state at a venue
class Venue:
    def __init__(self, ask, ask_size, fee=FEE, rebate=REBATE):
        self.ask = ask
        self.ask_size = ask_size
        self.fee = fee
        self.rebate = rebate

# Computing cost of a given allocation strategy
def compute_cost(split, venues, order_size, λo, λu, θ):
    executed = 0
    cash_spent = 0
    for i in range(len(venues)):
        exe = min(split[i], venues[i].ask_size)  # max fill possible
        executed += exe
        cash_spent += exe * (venues[i].ask + venues[i].fee)  # pay fee
        maker_rebate = max(split[i] - exe, 0) * venues[i].rebate  # rebate for unfilled
        cash_spent -= maker_rebate

    # Penalizing underfill, overfill, and queue risk
    underfill = max(order_size - executed, 0)
    overfill = max(executed - order_size, 0)
    risk_pen = θ * (underfill + overfill)
    cost_pen = λu * underfill + λo * overfill
    return cash_spent + risk_pen + cost_pen

# Finding the best allocation of shares across venues
def allocate(order_size, venues, λo, λu, θ):
    splits = [[]]
    # Generating all combinations of share splits per venue
    for v in range(len(venues)):
        new_splits = []
        for alloc in splits:
            used = sum(alloc)
            max_v = min(order_size - used, venues[v].ask_size)
            for q in range(0, max_v + 1, STEP):
                new_splits.append(alloc + [q])
        splits = new_splits

    # Select the allocation with the lowest cost
    best_cost = float('inf')
    best_split = []
    for alloc in splits:
        if sum(alloc) != order_size:
            continue
        cost = compute_cost(alloc, venues, order_size, λo, λu, θ)
        if cost < best_cost:
            best_cost = cost
            best_split = alloc
    return best_split, best_cost

# Runming the full backtest over all parameter combinations
def run_backtest(param_grid):
    best_result = None
    for λo, λu, θ in param_grid:
        shares_remaining = ORDER_SIZE
        total_cost = 0
        ts_vs_cost = []  # for plotting cumulative cost

        # Go over each timestamp and make decisions
        for ts, snapshot in snapshots:
            if shares_remaining <= 0:
                break
            venues = [Venue(row.ask_px_00, row.ask_sz_00) for row in snapshot.itertuples()]
            alloc, _ = allocate(shares_remaining, venues, λo, λu, θ)
            fill = 0
            cost = 0
            for i, qty in enumerate(alloc):
                executed = min(qty, venues[i].ask_size)
                fill += executed
                cost += executed * (venues[i].ask + venues[i].fee)
            shares_remaining -= fill
            total_cost += cost
            ts_vs_cost.append((ts, total_cost))

        avg_price = total_cost / ORDER_SIZE
        if best_result is None or total_cost < best_result['cost']:
            best_result = {
                'params': (λo, λu, θ),
                'cost': total_cost,
                'avg_price': avg_price,
                'time_series': ts_vs_cost
            }
    return best_result

# Best-Ask strategy
def best_ask_strategy():
    shares_remaining = ORDER_SIZE
    total_cost = 0
    for _, snapshot in snapshots:
        if shares_remaining <= 0:
            break
        snapshot_sorted = snapshot.sort_values(by='ask_px_00')
        for row in snapshot_sorted.itertuples():
            qty = min(row.ask_sz_00, shares_remaining)
            total_cost += qty * row.ask_px_00
            shares_remaining -= qty
            if shares_remaining <= 0:
                break
    return total_cost / ORDER_SIZE, total_cost

# TWAP: splitting shares evenly over time, regardless of venue liquidity
def twap_strategy():
    total_cost = 0
    shares_remaining = ORDER_SIZE
    num_snapshots = len(snapshots)
    shares_per_step = ORDER_SIZE // num_snapshots
    leftover = ORDER_SIZE % num_snapshots

    for i, (_, snapshot) in enumerate(snapshots):
        if shares_remaining <= 0:
            break
        shares_to_trade = shares_per_step + (1 if i < leftover else 0)
        snapshot_sorted = snapshot.sort_values(by='ask_px_00')
        for row in snapshot_sorted.itertuples():
            qty = min(row.ask_sz_00, shares_to_trade)
            total_cost += qty * row.ask_px_00
            shares_to_trade -= qty
            shares_remaining -= qty
            if shares_to_trade <= 0 or shares_remaining <= 0:
                break
    avg_price = total_cost / ORDER_SIZE
    return avg_price, total_cost

# VWAP: allocating based on ask size proportions
def vwap_strategy():
    total_cost = 0
    shares_remaining = ORDER_SIZE
    for _, snapshot in snapshots:
        if shares_remaining <= 0:
            break
        venue_sizes = snapshot['ask_sz_00'].values
        total_size = np.sum(venue_sizes)
        if total_size == 0:
            continue
        proportions = venue_sizes / total_size
        snapshot = snapshot.reset_index(drop=True)
        for i, row in snapshot.iterrows():
            alloc = int(round(proportions[i] * ORDER_SIZE))
            qty = min(row.ask_sz_00, min(alloc, shares_remaining))
            total_cost += qty * row.ask_px_00
            shares_remaining -= qty
            if shares_remaining <= 0:
                break
    avg_price = total_cost / ORDER_SIZE
    return avg_price, total_cost

# Calculating savings vs a baseline in basis points (bps)
def savings_bps(base, opt):
    return ((base - opt) / base) * 10000

# Defining parameter grid for tuning
lambda_over_vals = [0.01, 0.05]
lambda_under_vals = [0.05, 0.1]
theta_vals = [0.001, 0.005]
param_grid = list(itertools.product(lambda_over_vals, lambda_under_vals, theta_vals))

# Run main strategy and baselines
best_result = run_backtest(param_grid)
best_ask_avg, best_ask_total = best_ask_strategy()
twap_avg, twap_total = twap_strategy()
vwap_avg, vwap_total = vwap_strategy()

# Assembling final results as JSON output
output_full = {
    "best_parameters": {
        "lambda_over": best_result['params'][0],
        "lambda_under": best_result['params'][1],
        "theta_queue": best_result['params'][2]
    },
    "optimized_result": {
        "total_cash_spent": round(best_result['cost'], 2),
        "avg_fill_price": round(best_result['avg_price'], 4)
    },
    "best_ask_baseline": {
        "total_cash_spent": round(best_ask_total, 2),
        "avg_fill_price": round(best_ask_avg, 4),
        "savings_bps": round(savings_bps(best_ask_avg, best_result['avg_price']), 2)
    },
    "twap_baseline": {
        "total_cash_spent": round(twap_total, 2),
        "avg_fill_price": round(twap_avg, 4),
        "savings_bps": round(savings_bps(twap_avg, best_result['avg_price']), 2)
    },
    "vwap_baseline": {
        "total_cash_spent": round(vwap_total, 2),
        "avg_fill_price": round(vwap_avg, 4),
        "savings_bps": round(savings_bps(vwap_avg, best_result['avg_price']), 2)
    }
}

# Plotting cumulative cost over time for optimized strategy
timestamps, costs = zip(*best_result['time_series'])
plt.plot(timestamps, costs, label="Optimized Strategy")
plt.title('Cumulative Cost Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Cumulative Cost')
plt.legend()
plt.savefig("results.png")  # Save as PNG

# Outputing the result as JSON
print(json.dumps(output_full, indent=4))